name: Continuous Test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js ${{ matrix.node-version }}      
        uses: actions/setup-node@v1
      - name: install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-slackmsg
       # Run postman collection
      - name: run postman collection   
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}     
        run: |
          newman run Vivifyscrum.postman_collection.json -e stage-env.json --suppress-exit-code -r cli,slackmsg --reporter-slackmsg-webhookurl ${{SLACK_WEBHOOK_URL}}